config/routes.rb
Rails.application.routes.draw do
  SEO_NAME_PATTERN = /([0-9]+)[a-z0-9-]*/

  root 'welcome#homepage'

  # Account management
  get '/account', to: 'account#overview', as: 'account'
  get '/account/email-address', to: 'account#email', as: 'account_email'
  get '/account/password', to: 'account#password', as: 'account_password'
  get '/account/profile-information', to: 'account#profile', as: 'account_profile'
  get '/account/profile-picture', to: 'account#picture', as: 'account_picture'

  # Profiles
  get '/profile/:id', to: 'profile#show', as: 'profile', constraints: { id: SEO_NAME_PATTERN }

  # Forums
  get '/forums', to: 'forums#index', as: 'forums'
  get '/forum/:id', to: 'forums#show', as: 'forum', constraints: { id: SEO_NAME_PATTERN }

  # Topics
  get '/topic/:id', to: 'topics#show', as: 'topic', constraints: { id: SEO_NAME_PATTERN }
  get '/topic/start/:forum_id', to: 'topics#start', as: 'start_topic'
  post '/topic/start/:forum_id', to: 'topics#create', as: 'create_topic'
  get '/topic/edit/:id', to: 'topics#edit', as: 'edit_topic'
  post '/topic/edit/:id', to: 'topics#update', as: 'update_topic'

  # Posts
  get '/post/:id', to: 'posts#show', as: 'post'
  get '/post/reply/:topic_id', to: 'posts#reply', as: 'post_reply'
  post '/post/reply/:topic_id', to: 'posts#create', as: 'post_create'
  get '/post/edit/:id', to: 'posts#edit', as: 'post_edit'
  post '/post/edit/:id', to: 'posts#update', as: 'post_update'

  devise_scope :user do
    # Registrations
    get '/sign-up' => 'users/registrations#new', as: 'new_user_registration'
    post '/sign-up' => 'users/registrations#create', as: 'user_registration'

    # Sessions
    get '/sign-in' =>'users/sessions#new', as: 'new_user_session'
    post '/sign-in' => 'users/sessions#create', as: 'user_session'
    delete '/sign-out' => 'users/sessions#destroy', as: 'destroy_user_session'
  end

  devise_for :users, skip: [:sessions, :registrations], controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  belongs_to :category, class_name: 'Forum', foreign_key: 'parent_id'
  belongs_to :last_post, class_name: 'Post', foreign_key: 'last_post_id'
  has_many :forums, foreign_key: 'parent_id'
  has_many :topics
  has_many :posts, through: :topics

  validates_presence_of :seo_name

  @stack_last_post = nil

  def to_param
    "#{id}-#{seo_name}"
  end

  def name= (name)
    write_attribute :name, name
    set_seo_name
  end

  def num_topics_stack
    if forums.length > 0
      stack_topics = Forum.where('parent_id = ?', id).sum(:num_topics)
    end

    num_topics + (stack_topics || 0)
  end

  def num_posts_stack
    if forums.length > 0
      stack_posts = Forum.where('parent_id = ?', id).sum(:num_posts)
    end

    num_posts + (stack_posts || 0)
  end

  def last_post_stack
    # if forums.length > 0 and @stack_last_post.nil?
    #   @stack_last_post = Forum.where('parent_id = ?', id).order('last_post_id desc').first
    # end

    # if !@stack_last_post.nil? and (last_post.nil? or @stack_last_post.last_post.post_date > last_post.post_date)
    #   @stack_last_post.last_post
    # else
    #   last_post
    # end

    last_post
  end

  # This method will update the last post
  # to whichever post is the second most recent.
  def update_last_post
    return unless posts.length > 1
    write_attribute :last_post_id, posts[-2].id
  end

  private
    def set_seo_name
      self.seo_name = name.parameterize
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @categories = Forum.joins(:forums).where('forums.parent_id is null').uniq
  end

  def show
    @forum  = Forum.find params[:id]

    # Doesn't use the last_post.post_date because newly created topics to not have a last_post!
    @topics = Topic.joins(:replies).where('topics.forum_id = ?', @forum.id).order('posts.post_date DESC').uniq
  end
end

app/helpers/forum_helper.rb
module ForumHelper
  def render_subforums (subforums)
    render 'forums/subforums', forums: subforums
  end
end

app/views/forums/_subforums.html.erb
<% for forum in forums %>
  <div class="category__forum">
    <div class="category__forumInfo">
      <div class="category__forumName">
        <%= link_to forum.name, forum_path(forum) %>
      </div>
      <% if not forum.description.nil? %>
        <div class="category__forumDesc">
          <%= forum.description %>
        </div>
      <% end %>
      <% if forum.forums.length > 0 %>
        <div class="category__forumSubs">
          <ul>
            <% for sub in forum.forums %>
              <li><%= link_to sub.name, forum_path(sub) %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="category__forumStats">
      <% if not forum.last_post_stack.nil? %>
        <%= pluralize forum.num_topics_stack, 'topic' %> and <%= pluralize forum.num_posts, 'reply' %>, the last posted by <%= link_to forum.last_post_stack.author.username, profile_path(forum.last_post_stack.author) %> <%= short_time forum.last_post_stack.post_date %>
      <% else %>
        No posts have been made.
      <% end %>
    </div>
  </div>
<% end %>

app/views/forums/index.html.erb
<% title 'Forums' %>

<% for category in @categories %>
  <div class="forums__category">
    <h3 class="category__title"><%= link_to category.name, forum_path(category) %></h3>
    <%= render_subforums category.forums %>
  </div>
<% end %>

app/views/forums/show.html.erb
<% title @forum.name %>

<% if @forum.forums.length > 0 %>
  <div class="category category--subforums">
    <h3><%= 'Subforum'.pluralize @forum.forums.length %></h3>
    <%= render_subforums @forum.forums %>
  </div>
<% end %>

<% if user_signed_in? %>
  <div class="forum__buttonRow">
    <ul>
      <li><%= link_to 'Create new topic', create_topic_path(@forum.id) %></li>
    </ul>
  </div>
<% end %>

<% if !@forum.category.nil? %>
  <h3>Topics</h3>

  <% if @topics.length == 0 %>
    <div class="forum__topic forum__topic--noTopics">This forum does not have any topics.</div>
  <% end %>

  <% for topic in @topics %>
    <div class="forum__topic">
      <div class="forum__topicInfo">
        <div class="forum__topicName">
          <%= link_to topic.name, topic_path(topic) %>
        </div>
        Started by <%= link_to topic.author.username, profile_path(topic.author) %> <%= short_time topic.post_date %>
      </div>
      <div class="forum__topicStats">
        <% if not topic.last_post.nil? %>
          <%= pluralize topic.num_posts, 'reply' %>, the last posted by <%= link_to topic.last_post.author.username, profile_path(topic.last_post.author) %> <%= short_time topic.last_post.post_date %>
        <% else %>
          No replies have been posted.
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>