config/routes.rb
Rails.application.routes.draw do
  SEO_NAME_PATTERN = /([0-9]+)[a-z0-9-]*/

  root 'welcome#homepage'

  # Account management
  get '/account', to: 'account#overview', as: 'account'
  get '/account/email-address', to: 'account#email', as: 'account_email'
  get '/account/password', to: 'account#password', as: 'account_password'
  get '/account/profile-information', to: 'account#profile', as: 'account_profile'
  get '/account/profile-picture', to: 'account#picture', as: 'account_picture'

  # Profiles
  get '/profile/:id', to: 'profile#show', as: 'profile', constraints: { id: SEO_NAME_PATTERN }

  # Forums
  get '/forums', to: 'forums#index', as: 'forums'
  get '/forum/:id', to: 'forums#show', as: 'forum', constraints: { id: SEO_NAME_PATTERN }

  # Topics
  get '/topic/:id', to: 'topics#show', as: 'topic', constraints: { id: SEO_NAME_PATTERN }
  get '/topic/start/:forum_id', to: 'topics#start', as: 'start_topic'
  post '/topic/start/:forum_id', to: 'topics#create', as: 'create_topic'
  get '/topic/edit/:id', to: 'topics#edit', as: 'edit_topic'
  post '/topic/edit/:id', to: 'topics#update', as: 'update_topic'

  # Posts
  get '/post/:id', to: 'posts#show', as: 'post'
  get '/post/reply/:topic_id', to: 'posts#reply', as: 'post_reply'
  post '/post/reply/:topic_id', to: 'posts#create', as: 'post_create'
  get '/post/edit/:id', to: 'posts#edit', as: 'post_edit'
  post '/post/edit/:id', to: 'posts#update', as: 'post_update'

  devise_scope :user do
    # Registrations
    get '/sign-up' => 'users/registrations#new', as: 'new_user_registration'
    post '/sign-up' => 'users/registrations#create', as: 'user_registration'

    # Sessions
    get '/sign-in' =>'users/sessions#new', as: 'new_user_session'
    post '/sign-in' => 'users/sessions#create', as: 'user_session'
    delete '/sign-out' => 'users/sessions#destroy', as: 'destroy_user_session'
  end

  devise_for :users, skip: [:sessions, :registrations], controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :forum
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :last_post, class_name: 'Post', foreign_key: 'last_post_id'
  has_many :replies, class_name: 'Post'

  validates_presence_of :name, :forum, :author

  before_save :set_post_date, on: :create
  after_create :update_forum_stats_for_create

  after_destroy :update_forum_stats_for_destroy

  def to_param
    "#{id}-#{seo_name}"
  end

  def name= (name)
    write_attribute :name, name
    set_seo_name
  end

  private
    def set_post_date
      self.post_date ||= Time.new
    end

    def set_seo_name
      self.seo_name = name.parameterize
    end

    def update_forum_stats_for_create
      forum.increment :num_topics
      forum.save
    end

    def update_forum_stats_for_destroy
      forum.decrement :num_topics
      forum.save
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_session, only: [:start, :create, :edit, :update]

  def show
    @topic = Topic.find params[:id]
  end

  def start
    @forum = Forum.find params[:forum_id]
    @topic = Topic.new
    @post  = Post.new

    render :start
  end

  def create
    @forum = Forum.find params[:forum_id]
    @topic = Topic.new topic_params
    @post  = Post.new post_params

    @topic.assign_attributes({ forum: @forum, author: current_user })
    @post.assign_attributes({ topic: @topic, author: current_user, is_first: true })

    if @topic.save
      if @post.save
        redirect_to @topic, notice: 'Posted your topic.'
        return
      end

      @topic.destroy
    end

    render :start
  end

  def edit
    @topic = Topic.find params[:id]
    @post  = Post.where('topic_id = ?', @topic.id).first
  end

  def update
    @topic = Topic.find params[:id]
    @post  = Post.where('topic_id = ?', @topic.id).first

    @topic.assign_attributes topic_params
    @post.assign_attributes post_params

    if @topic.valid? and @post.valid?
      @topic.save
      @post.save

      redirect_to @topic, notice: 'Saved your changes.'
    else
      render 'edit'
    end
  end

  private
    def topic_params
      params.require(:topic).permit(:name)
    end

    def post_params
      params.require(:topic).permit(post: [:content])[:post]
    end
end

app/views/topics/_form.html.erb
<div class="formWrap">
  <% all_errors = @topic.errors.full_messages + @post.errors.full_messages %>

  <% if all_errors.length > 0 %>
    <ul>
      <% for error_msg in all_errors %>
        <li><%= error_msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <%= form_for :topic, url: action do |topic_form| %>
    <div class="formWrap__label">
      <%= topic_form.label :name %>
    </div>
    <div class="formWrap__field">
      <%= topic_form.text_field :name, autofocus: true, disabled: (not @topic.post_date.nil? and @topic.post_date > (Time.new + 3600)) %>
    </div>

    <%= topic_form.fields_for @post do |post_form| %>
      <div class="formWrap__label">
        <%= post_form.label :content %>
      </div>
      <div class="formWrap__field">
        <%= post_form.text_area :content, class: 'wysiwyg' %>
      </div>
    <% end %>

    <div class="formWrap__actions">
      <% case action_name %>
        <% when 'start', 'create' %>
          <%= topic_form.submit "Create Topic" %>
        <% when 'edit', 'update' %>
          <%= topic_form.submit "Save Changes" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<% title 'Editing Topic' %>

<%= render 'form', action: update_topic_path(@topic) %>

app/views/topics/show.html.erb
<% title @topic.name %>

<% if user_signed_in? %>
  <div class="topic__buttonRow">
    <ul>
      <li><%= link_to 'Post a reply', post_reply_path(@topic) %></li>
    </ul>
  </div>
<% end %>

<% for post in @topic.replies %>
  <a name='post_<%= post.id %>'></a>

  <div class="topic__reply">
    <div class="topic__replyAuthor">
      <%= image_tag post.author.gravatar_url, class: 'topic__replyAuthorPicture' %>
      <div class="topic__replyAuthorInfo">
        <%= link_to post.author.username, profile_path(post.author) %>
        <div class="topic__replyAuthorReplyCount">
          <%= number_with_delimiter post.author.num_posts %> <%= 'post'.pluralize post.author.num_posts %>
        </div>
      </div>
    </div>

    <div class="topic__replyContent">
      <div class="topic__replyPostDate">
        <% if post.is_first? %>Started<% else %>Posted<% end %> <%= short_time post.post_date %>
      </div>

      <div class="topic__replyText">
        <%= simple_format post.content.bbcode_to_html %>
      </div>

      <% if user_signed_in? %>
        <div class="topic__replyOptions">
          <ul>
            <% if current_user.is_moderator? or post.author == current_user %>
              <% if post.is_first? %>
                <% edit_path = edit_topic_path(@topic) %>
              <% end %>

              <li><%= link_to('Edit', edit_path || post_edit_path(post)) %></li>
            <% end %>

            <% if not post.is_first? %>
              <li><%= link_to('Reply', forums_path) %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/topics/start.html.erb
<% title 'Creating New Topic' %>

<%= render 'form', action: create_topic_path(@forum) %>