config/routes.rb
Rails.application.routes.draw do
  SEO_NAME_PATTERN = /([0-9]+)[a-z0-9-]*/

  root 'welcome#homepage'

  # Account management
  get '/account', to: 'account#overview', as: 'account'
  get '/account/email-address', to: 'account#email', as: 'account_email'
  get '/account/password', to: 'account#password', as: 'account_password'
  get '/account/profile-information', to: 'account#profile', as: 'account_profile'
  get '/account/profile-picture', to: 'account#picture', as: 'account_picture'

  # Profiles
  get '/profile/:id', to: 'profile#show', as: 'profile', constraints: { id: SEO_NAME_PATTERN }

  # Forums
  get '/forums', to: 'forums#index', as: 'forums'
  get '/forum/:id', to: 'forums#show', as: 'forum', constraints: { id: SEO_NAME_PATTERN }

  # Topics
  get '/topic/:id', to: 'topics#show', as: 'topic', constraints: { id: SEO_NAME_PATTERN }
  get '/topic/start/:forum_id', to: 'topics#start', as: 'start_topic'
  post '/topic/start/:forum_id', to: 'topics#create', as: 'create_topic'
  get '/topic/edit/:id', to: 'topics#edit', as: 'edit_topic'
  post '/topic/edit/:id', to: 'topics#update', as: 'update_topic'

  # Posts
  get '/post/:id', to: 'posts#show', as: 'post'
  get '/post/reply/:topic_id', to: 'posts#reply', as: 'post_reply'
  post '/post/reply/:topic_id', to: 'posts#create', as: 'post_create'
  get '/post/edit/:id', to: 'posts#edit', as: 'post_edit'
  post '/post/edit/:id', to: 'posts#update', as: 'post_update'

  devise_scope :user do
    # Registrations
    get '/sign-up' => 'users/registrations#new', as: 'new_user_registration'
    post '/sign-up' => 'users/registrations#create', as: 'user_registration'

    # Sessions
    get '/sign-in' =>'users/sessions#new', as: 'new_user_session'
    post '/sign-in' => 'users/sessions#create', as: 'user_session'
    delete '/sign-out' => 'users/sessions#destroy', as: 'destroy_user_session'
  end

  devise_for :users, skip: [:sessions, :registrations], controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :forum, polymorphic: :topic
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  validates_presence_of :topic, :author, :content

  before_save :set_post_date, on: :create
  after_create :update_stats_for_create

  private
    def set_post_date
      self.post_date ||= Time.new
    end

    def update_stats_for_create
      author.increment :num_posts
      author.save

      topic_vals = { last_post: self }
      forum_vals = { last_post: self }

      if not is_first?
        forum_vals[:num_posts] = topic.forum.num_posts + 1
        
        topic.update({ last_post: self, num_posts: topic.num_posts + 1 })
      end

      topic.forum.update forum_vals
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    post = Post.find params[:id]
    redirect_to post.topic
  end

  def reply
    @topic = Topic.find params[:topic_id]
    @post  = Post.new
  end

  def create
    @topic = Topic.find params[:topic_id]
    @post  = Post.new post_params

    @post.assign_attributes({ topic: @topic, author: current_user })

    if @post.save
      redirect_to @post, notice: 'Posted your reply.'
    else
      render 'reply'
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]

    @post.assign_attributes post_params

    if @post.save
      redirect_to @post, notice: 'Saved your changes.'
    else
      render 'reply'
    end
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_path (post)
    "#{topic_path post.topic}#post_#{post.id}"
  end
end

app/views/posts/_form.html.erb
<div class="formWrap">
  <% all_errors = @post.errors.full_messages %>

  <% if all_errors.length > 0 %>
    <ul>
      <% for error_msg in all_errors %>
        <li><%= error_msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for :post, url: action do |post_form| %>
    <div class="formWrap__label">
      <%= post_form.label :content %>
    </div>
    <div class="formWrap__field">
      <%= post_form.text_area :content, class: 'wysiwyg' %>
    </div>

    <div class="formWrap__actions">
      <% case action_name %>
        <% when 'reply', 'create' %>
          <%= post_form.submit "Post Reply" %>
        <% when 'edit', 'update' %>
          <%= post_form.submit "Save Changes" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% title 'Editing a Reply' %>

<%= render 'form', action: post_update_path(@post) %>

app/views/posts/reply.html.erb
<% title 'Posting a Reply' %>

<%= render 'form', action: post_create_path(@topic) %>